# Prettier configuration
overrides:
  - files:
    - "*.java"
    - "*.xml"
    options:
      endOfLine: crlf
      printWidth: 140
      tabWidth: 2
      useTabs: false
      trailingComma: "es5"
      semi: false
      singleQuote: true
      bracketSpacing: false
      arrowParens: "always"
